#Dinesh Karnati 

# 5
#Performs hyperparameter tuning for KNN classifier on Iris dataset.
#Tuning hyperparameters of knn classifier (classif.knn) Using cross-validation resampling and grid search, with a focus on optimizing the k parameter for model accuracy

# Load the Iris dataset
data(iris)

# Create a classification task
irisTask <- makeClassifTask(data = iris, target = "Species") 
knnParamSpace <- makeParamSet(makeDiscreteParam("k", values = 1:25))

gridSearch <- makeTuneControlGrid() # Define tuning control (grid search)

cvForTuning <- makeResampleDesc("RepCV", folds = 10, reps = 20) # Define cross-validation for tuning

# Tune hyperparameters
tunedK <- tuneParams("classif.knn", task = irisTask, 
                     resampling = cvForTuning, 
                     par.set = knnParamSpace, 
                     control = gridSearch)

tunedK

# Best hyperparameters (value of k)
tunedK$x

knnTuningData <- generateHyperParsEffectData(tunedK)

# Plot hyperparameter tuning curve
plotHyperParsEffect(knnTuningData, x = "k", y = "mmce.test.mean",
                    plot.type = "line") +
  theme_bw()

tunedKnn <- setHyperPars(makeLearner("classif.knn"), par.vals = tunedK$x)
# Train the final model with tuned hyperparameters
tunedKnnModel <- train(tunedKnn, irisTask)
